// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCF3ylklngWHnj0p901dx3CmZgykGt5CJU',
    appId: '1:903437557620:android:c73921b68ec76681dc5621',
    messagingSenderId: '903437557620',
    projectId: 'fypparaiso',
    storageBucket: 'fypparaiso.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCF3ylklngWHnj0p901dx3CmZgykGt5CJU',
    appId: '1:903437557620:ios:d3727421a4469763dc5621',
    messagingSenderId: '903437557620',
    projectId: 'fypparaiso',
    storageBucket: 'fypparaiso.appspot.com',
    androidClientId: '700322154383-o1dlugndt11qhvlof8rscqh63jh6dvi2.apps.googleusercontent.com',
    iosClientId: '700322154383-smumdhmq92idrrodulgeq953kqgrviql.apps.googleusercontent.com',
    iosBundleId: 'com.example.fypParaiso',
  );
}
